### ISSUE TITLE
Lexing error with dash in a comment

### ISSUE THREAD

**Issue by mccartney** [bertramdev/hcl4j#22]
The following `.tf` file results in a `HCLParserException`:
```
terraform {
  backend "s3" {
    bucket = "my-configuration"     # in my-main account
    key = "my-terraform-state"
    region = "us-west-1"
  }
}
```
in hcl4j 0.6.1 while works fine in hcl4j 0.4.4.

## Exception
```
com.bertramlabs.plugins.hcl4j.HCLParserException: Illegal character <(=) - state: 14> found on line: 4 col: 9
at com.bertramlabs.plugins.hcl4j.HCLLexer.yylex(HCLLexer.java:1388)	
at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:307)	
at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:274)	
at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:198)	
at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:181)	
at com.my.code.ParsingTerraform$.loadFile(ParsingTerraform.scala:40)
```

## Workaround
Move the comment to separate line. This works fine:
```
terraform {
  backend "s3" {
    # in my-main account
    bucket = "my-configuration"
    key = "my-terraform-state"
    region = "us-west-1"
  }
}
```

**Comment by davydotcom** [comment]
I just tried the above example with no error on 06.2+ seems it was fixed?

**Comment by mccartney** [comment]
I continue to see the problem (with both my real code and the artificial one pasted above) after upgrading 0.6.3. Also the workaround continues to work, so not a big deal.

```
Caused by: com.bertramlabs.plugins.hcl4j.HCLParserException: Illegal character <(=) - state: 14> found on line: 4 col: 9
	at app//com.bertramlabs.plugins.hcl4j.HCLLexer.yylex(HCLLexer.java:1388)
	at app//com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:307)
	at app//com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:274)
	at app//com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:198)
	at app//com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:181)
	at app//REDACTED.ParsingTerraform$.loadFile(ParsingTerraform.scala:40)
```

@davydotcom I suggest to re-open this issue.

**Comment by davydotcom** [comment]
@mccartney i just tried the exact copy of your code at the start and put into the HCLParserSpec test and it passed without fault.

**Comment by mccartney** [comment]
I think we can close the issue.

**Comment by davydotcom** [comment]
Ah yes, so the gradle upgrade caused tests to silently not run this was my problem. All good now thanks for reporting!

**Comment by mccartney** [comment]
(no action needed, just for completeness)

I've just checked my real code and `0.6.4` of hcl4j still suffers. So I suppose the actual fix for this issue was done in https://github.com/bertramdev/hcl4j/commit/70c63db901f0df4571eab91bb9b1a790b310e686 (not released yet as of now).

**Comment by mccartney** [comment]
I can confirm `0.6.5` works fine now. Thanks again for fixing this.
