### ISSUE TITLE
Infinite loop resulting in StackOverflowError when referring to resource properties

### ISSUE THREAD

**Issue by mccartney** [bertramdev/hcl4j#24]
The following `.tf` file results in an infinite loop and `StackOverflowError` as a consequence:
```
resource "aws_acm_certificate" "cert_1" {
  domain_name = "example.com"
  subject_alternative_names = ["example.com"]
  validation_method = "DNS"
}
locals {
 c = aws_acm_certificate.cert_1.domain_validation_options
}
```
in hcl4j 0.6.1 while it works fine in hcl4j 0.4.4.

## Exception head
```
com.bertramlabs.plugins.hcl4j.HCLMyParserSpec > should generate Map from hcl FAILED
    java.lang.StackOverflowError
        at org.apache.groovy.json.internal.SimpleCache.get(SimpleCache.java:44)
        at org.apache.groovy.json.internal.CharBuf.addInt(CharBuf.java:140)
        at groovy.json.DefaultJsonGenerator.writeNumber(DefaultJsonGenerator.java:127)
        at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:194)
        at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
        at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
        at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
        at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
```

**Comment by davydotcom** [comment]
This is due to using the groovy JsonOutput which hits an evaluation symbol which has a parent/child tree. really not intended to use this but did in some tests that it was safe on. I did however fix ObjectMapper to properly handle depth and @JsonIgnore annotations on the symbol objects for jackson-databind

**Comment by davydotcom** [comment]
if you want to make it work i believe as of groovy 2.5 plus you can use this json generator options
```
def generator = new groovy.json.JsonGenerator.Options()
    .excludeFieldsByName('parent')
    .build()
generator.toJson(results)
```

**Comment by mccartney** [comment]
I no longer observe the problem (in either my real code or the artificial example pasted above) after upgrading to 0.6.3. So to be honest, I didn't try your workaround.

Thank you!
