### ISSUE TITLE
ArrayList cannot be cast to Map

### ISSUE THREAD

**Issue by mccartney** [bertramdev/hcl4j#25]
The following `.tf` file results in a `ClassCastException`:
```
locals {
  domains = ["a.example.com", "b.example.com"]
}

resource "aws_acm_certificate" "cert_1" {
  for_each = local.domains
  domain_name = each.key
  subject_alternative_names = [each.key]
  validation_method = "DNS"
}
locals {
 c = aws_acm_certificate.cert_1["a.example.com"].domain_validation_options
}
```
in hcl4j 0.6.1 while it works fine in hcl4j 0.4.4.

## Exception head
```
    java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
        at com.bertramlabs.plugins.hcl4j.HCLParser.processEvaluation(HCLParser.java:875)
        at com.bertramlabs.plugins.hcl4j.HCLParser.processSymbolPass2(HCLParser.java:459)
        at com.bertramlabs.plugins.hcl4j.HCLParser.processSymbolPass2(HCLParser.java:641)
        at com.bertramlabs.plugins.hcl4j.HCLParser.processSymbolPass2(HCLParser.java:421)
        at com.bertramlabs.plugins.hcl4j.HCLParser.processSymbolPass2(HCLParser.java:421)
        at com.bertramlabs.plugins.hcl4j.HCLParser.processSymbolPass2(HCLParser.java:421)
        at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:323)
        at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:121)
        at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:108)
	at com.mycode.MyCode(MyCode.java:19)
```

## Workaround
Merge the two `locals{}` into one:
```
locals {
  domains = ["a.example.com", "b.example.com"]
  c = aws_acm_certificate.cert_1["a.example.com"].domain_validation_options
}

resource "aws_acm_certificate" "cert_1" {
  for_each = local.domains
  domain_name = each.key
  subject_alternative_names = [each.key]
  validation_method = "DNS"
}
```
and the `ClassCastException` goes away.
(and you land with #24 which I think is another problem)

**Comment by davydotcom** [comment]
good catch this is because per HCL when you have 2 blocks with the same name the blocks combine into a collection of. blocks. In the case of the "locals" block it is special and should flat merge per tf (not hcl). I will fix this

**Comment by davydotcom** [comment]
ok have this fixed for 0.6.3

**Comment by mccartney** [comment]
Thanks for this and other fixes.
I will try them when I am back at work.

**Comment by davydotcom** [comment]
No problem! Thanks for the feedback !

**Comment by mccartney** [comment]
I can confirm I no longer see the problem in `0.6.3`. Thanks for a quick fix!
