### ISSUE TITLE
parsing failure on seeing `\`

### ISSUE THREAD

**Issue by vaibhav-si** [bertramdev/hcl4j#3]
Here is the content of my tf file -

access_log_settings {
    destination_arn = "${aws_cloudwatch_log_group.api_gw_cloudwatch.arn}"
    format          = "${replace(file("api_log_format.json"), "\n", "")}"
}

And parsing fails when it encounters "\". 

Stacktrace - 

Exception in thread "main" com.bertramlabs.plugins.hcl4j.HCLParserException: Illegal character <(\) - state: 26> found on line: 3 col: 64
	at com.bertramlabs.plugins.hcl4j.HCLLexer.yylex(HCLLexer.java:993)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:186)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:173)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:113)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:74)
	at Main.isRemoteStateConfigured(Main.java:17)
	at Main.main(Main.java:30)

**Comment by davydotcom** [comment]
String interpolation is now evaluated as of 0.6.0 and this should now pass
