### ISSUE TITLE
Processing Error when having colon char in value

### ISSUE THREAD

**Issue by koalalam** [bertramdev/hcl4j#35]
Version: 0.7.2

The first test `testValueWithoutColon` passes while the second test `testValueWithColon` fails.

```java
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import com.bertramlabs.plugins.hcl4j.HCLParser;
import org.junit.jupiter.api.Test;

class HCL4JBugReport {

    @Test
    void testValueWithoutColon() {
        String valueWithoutColon = """
    variable "variable1"{
      default = [
        {
          key = "someKey"
          attributes = {
            "attribute1" = "valueWithoutColon"
          }
        }
      ]
    }""";
        HCLParser parser = new HCLParser();
        assertDoesNotThrow(
                () -> parser.parse(valueWithoutColon));
    }


    @Test
    void testValueWithColon() {
        String valueWithColon = """
    variable "variable1"{
      default = [
        {
          key = "someKey"
          attributes = {
            "attribute1" = ":valueWithColon"
          }
        }
      ]
    }""";
        HCLParser parser = new HCLParser();
        assertDoesNotThrow(
                () -> parser.parse(valueWithColon));
    }
}
```

```
05:58:10.274 [Test worker] ERROR com.bertramlabs.plugins.hcl4j.HCLParser - Error Parsing HCL...Illegal character <(=) - state: 22> found on line: 6 col: 22
com.bertramlabs.plugins.hcl4j.HCLParserException: Illegal character <(=) - state: 22> found on line: 6 col: 22
	at com.bertramlabs.plugins.hcl4j.HCLLexer.yylex(HCLLexer.java:1403) ~[hcl4j-0.7.2.jar:?]
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:302) ~[hcl4j-0.7.2.jar:?]
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:123) ~[hcl4j-0.7.2.jar:?]
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:110) ~[hcl4j-0.7.2.jar:?]
```

**Comment by davydotcom** [comment]
fixed in 0.9.0
