### ISSUE TITLE
Parsing Error with $ char in value present in for loop

### ISSUE THREAD

**Issue by amith-cognitree** [bertramdev/hcl4j#36]
Version: 0.7.3

In the below example `${key}` is causing the parsing error. It works fine if the value of `Name` attribute is set as "any string value"

```
locals {
  list = {for key in toset(["value1", "value2"]) :
    replace(key, ".", "_") =>
    {
      key = key
      tags = { Name = "${id}-${key}" }
  } }
}
```

This is noticed only when `for` loop is used the, parsing works fine in other cases for example - 
```
locals {
  dynamodb_table = "${csm-eks-tfstatelock} - ${sdf}"
}
```

Error Message
```
java.lang.RuntimeException: com.bertramlabs.plugins.hcl4j.HCLParserException: Illegal character <({) - state: 50> found on line: 6 col: 34
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:320)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:123)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:110)
```

**Comment by davydotcom** [comment]
lists were not supported until a later version. can you check this against 0.9.4?
