### ISSUE TITLE
"HCLParserException: Illegal character <(a) - state: 6>" passing a provider with alias

### ISSUE THREAD

**Issue by mccartney** [bertramdev/hcl4j#38]
The following code:
```
module "submodule" {
  source                 = "./submodule"
  providers              = {
    aws.us-west-2-infrastructure = aws.us-west-2-infrastructure
  }
}
```
fails with:
```
com.bertramlabs.plugins.hcl4j.HCLParserException: Illegal character <(a) - state: 6> found on line: 4 col: 5
        at com.bertramlabs.plugins.hcl4j.HCLLexer.yylex(HCLLexer.java:1403)
        at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:302)
        at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:276)
        at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:200)
        at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:183)
```
when running `new HCLParser().parse()` against it.

Using hcl4j 0.7.3

**Comment by mccartney** [comment]
The following works fine:
```
module "submodule" {
  source                 = "./submodule"
  providers              = {
    aws = aws.us-west-2-infrastructure
  }
}
```

**Comment by davydotcom** [comment]
fixing periods in attribute names done in 0.7.7 based on ID_Continue
