### ISSUE TITLE
Thank

### ISSUE THREAD

**Issue by voiddev** [bertramdev/hcl4j#79]
Thank you for the library!

I came across with the `java.util.ConcurrentModificationException` in a case when using Function and DataLookup. 
But during debugging I found that the issue is not related to concurrency. It looks like it is related to modification of `result` field during resolving callbacks.

Here is a Java example which throws this exception
```
public class JavaTestParser {

    public static void main(String[] args) {

        String content = "data \"local_file\" \"template\" {\n" +
                "  filename = \"${path.module}/template.json.tpl\"\n" +
                "  depends_on = [\"test\"]\n" +
                "}\n" +
                "\n" +
                "resource \"local_file\" \"json\" {\n" +
                "  filename = \"${path.module}/output.json\"\n" +
                "  content = templatefile(data.local_file.template.filename, {\n" +
                "    address = \"0.0.0.0\"\n" +
                "    port    = \"8080\"\n" +
                "  })\n" +
                "}\n" +
                "\n" +
                "module \"inner_module\" {\n" +
                "  source = \"./inner-module\"\n" +
                "}";

        HCLParser hclParser = getHclParser();

        try {

            Map schema = hclParser.parse(content);
            System.out.println(schema);

        } catch (HCLParserException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static HCLParser getHclParser() {
        HCLParser hclParser = new HCLParser();

        hclParser.registerDataLookup("local_file", (properties) -> {
            ConcurrentHashMap<String, Object> schema = new ConcurrentHashMap<>(properties);
            System.out.println("data lookup");
            return schema;
        });

        hclParser.registerFunction("templatefile", (arguments) -> {
            System.out.println("function");

            HashMap<String, String> result = new HashMap<>();
            result.put("test", "test");
            return result;
        });

        hclParser.registerFunction("file", (arguments) -> {
            System.out.println("function");
            return null;
        });

        return hclParser;
    }
}
```

terraform source from the example above :
```
data "local_file" "template" {
  filename = "${path.module}/template.json.tpl"
  depends_on = ["test"]
}

resource "local_file" "json" {
  filename = "${path.module}/output.json"
  content = templatefile(data.local_file.template.filename, {
    address = "0.0.0.0"
    port    = "8080"
  })
}

module "inner_module" {
  source = "./inner-module"
}
```

logs
```
Exception in thread "main" java.lang.RuntimeException: java.util.ConcurrentModificationException
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:345)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:136)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:123)
	at com.nc.quetzalcoatl.lazyplan.JavaTestParser.main(JavaTestParser.java:39)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:1046)
	at com.bertramlabs.plugins.hcl4j.HCLParser.parse(HCLParser.java:337)
	... 3 more

```

**Comment by davydotcom** [comment]
Publishing 0.9.4 with the resolution. Thanks for reporting!
